### ISSUE TITLE
Add support for 10.9

### ISSUE THREAD

**Issue by SaltySP** [jonschz/jellyfin-plugin-preventsleep#6]
Jellyfin 10.9 was released yesterday : [10.9](https://github.com/jellyfin/jellyfin/releases/tag/v10.9.0)

Now the plugin no longer loads properly:
![image](https://github.com/jonschz/jellyfin-plugin-preventsleep/assets/94236614/8bcef514-1617-4510-8b39-6ad5efb05376)

**Comment by jonschz** [comment]
This might have to do with Jellyfin moving to .NET 8. Will look into it. Thanks for reporting!

**Comment by jonschz** [comment]
Fixed in [v0.2.0](https://github.com/jonschz/jellyfin-plugin-preventsleep/releases/tag/v0.2.0), commit https://github.com/jonschz/jellyfin-plugin-preventsleep/commit/6499fb5dda89f31edc8367f262089f0b60220871

**Comment by SaltySP** [comment]
Thank you for the quick fix! <3
