### ISSUE TITLE
Music streams don't prevent sleep

### ISSUE THREAD

**Issue by RamiPPA** [jonschz/jellyfin-plugin-preventsleep#7]
When streaming music the computer is not prevented to sleep. It works well with video.

My setup:
Windows 11
Jellyfin server 10.9.11

**Comment by jonschz** [comment]
I took a look but could not reproduce it. Blocking sleep while streaming music seems to work as expected on my machine (Jellyfin Server 10.9.11, Prevent Sleep 0.2.0, Windows 10, both with the web client in Firefox on Windows 10 and on Android).

* What kind of client are you using to play back the music (web client in the browser or something else)? In the latter case, does this issue also appear when using the web client?
* If that does not lead anywhere, could you provide some logs?
  * In the plugin settings, set *Delay before unblocking sleep (in minutes)* to `1`.
  * Find the file `logging.default.json` in your config directory and set `"Default":` to `"Debug"`.
  * Restart your server and make sure that no devices are connecting automatically (this can clutter the logs).
  * Play back a video for a minute, then wait for two minutes.
  * Play back a music file for a minute, then wait for two minutes.
  * Go to *Administration -> Overview -> Log (or similar)`*, download the most recent log.
  * Remove any personal information (if necessary) and upload it here.

**Comment by RamiPPA** [comment]
Thanks for the reply jonschz ! 
I found the problem in the web client (using chrome) from a different pc, but  from the TV I didn't find this issue. 
I'm really busy these days but I'll try to reproduce the conditions which led to the problem and generate the logs that would bring some light to the issue.

BTW thanks a lot for the plugin. I wish that this eventually makes it to the holy "jellyfin core" which does nothing to help users with the carbon footprint.

**Comment by jonschz** [comment]
My hypothesis is that the affected client does not send the `PlaybackProgress` events for music, which this plugin relies on to tell that a stream is actively being watched. Another way to test that might the following:
* Start playing some music.
* Kill the browser mid-stream (e.g. using Task Manager)
* Reopen the browser and check if the song starts over from the beginning
* Check if the behaviour is different for videos

**Comment by RamiPPA** [comment]
I tried several times to reproduce the issue (trying to get the same conditions) and was not able to do so.

If I come across this again, I will report it with a full log.

Thanks
